buymeanoodle/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('creator.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path

from . import views


app_name = 'core'


urlpatterns = [
    path('', views.index, name='index'),
]

creator/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views


app_name = 'creator'


urlpatterns = [
    path('mypage/', views.mypage, name='mypage'),
    path('creators/', views.creators, name='creators'),
    path('creators/<int:pk>', views.creator, name='creator'),
    path('edit/', views.edit, name='edit'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='creator/login.html'), name='login')
]

core/models.py
from django.db import models

# Create your models here.

creator/models.py
from django.db import models
from django.contrib.auth.models import User


class Creator(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    image = models.ImageField(upload_to='uploads/creators')
    user = models.OneToOneField(User, related_name='creator', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    

creator/forms.py
from django.forms import ModelForm

from .models import Creator

class CreatorForm(ModelForm):
    class Meta:
        model = Creator
        fields = ('title', 'description', 'image',)
    

core/views.py
from django.shortcuts import render, redirect

from creator.models import Creator


def index(request):
    creators = Creator.objects.all()

    if request.user.is_authenticated:
        try:
            creator = request.user.creator
        except Exception:    
            return redirect('creator:edit')
        
    return render(request, 'core/index.html', {
        'creators':creators
    })

creator/views.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from .forms import CreatorForm
from . models import Creator


@login_required
def mypage(request):
    creator = request.user.creator

    return render(request, 'creator/mypage.html', {
        'creator': creator
    })

def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)

        if form.is_valid():
            form.save()

            return redirect('creator:login')

    else:    
        form = UserCreationForm()
    
    return render(request, 'creator/signup.html', {
        'form': form
    })

def creators(request):
    creators = Creator.objects.all()

    return render(request, 'creator/creators.html', {
        'creators': creators
    })

def creator(request, pk):
    creator = Creator.objects.get(pk=pk)

    return render(request, 'creator/creator.html', {
        'creator': creator
    })

def edit(request):
    try:
        creator = request.user.creator

        if request.method == "POST":
            form = CreatorForm(request.POST, request.FILES, instance=creator)

            if form.is_valid():
                form.save()

                return redirect('core:index')
        else:
            form = CreatorForm(instance=creator)
    except Exception:
        if request.method == "POST":
            form = CreatorForm(request.POST, request.FILES)

            if form.is_valid():
                creator = form.save(commit=False)  
                creator.user = request.user
                creator.save()

                return redirect('core:index')
        else:  
            form = CreatorForm()

    return render(request, 'creator/edit.html', {
        'form': form
    })

core/templates/core/base.html
<!doctype html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="cryptomus" content="7d2cdace" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <script src="https://cdn.tailwindcss.com"></script>

        <title>{% block title %}{% endblock %} | Buy me a noodle</title>
    </head>

    <body class="bg-slate-700">
        <nav class="py-8 px-8 flex flex-row items-center justify-between bg-slate-900">
            <div class="">
                <a href="{% url 'core:index' %}" class="text-2xl text-white font-bold">Buy me a noodle</a>
            </div>

            <div class="space-x-6">
                <a href="{% url 'creator:creators' %}" class="py-4 px-6 text-lg font-bold text-white">Creators</a>

                {% if not request.user.is_authenticated %}
                    <a href="{% url 'creator:login' %}" class="py-4 px-6 text-lg font-bold text-white">Log in</a>
                    <a href="{% url 'creator:signup' %}" class="py-4 px-6 text-lg font-bold text-white bg-sky-800 rounded-lg">Sign in</a>
                {% endif %}

                {% if request.user.is_authenticated %}
                    <a href="{% url 'creator:mypage' %}" class="py-4 px-6 text-lg font-bold text-white bg-sky-800 rounded-lg">My page</a>
                {% endif %}
            </div>
        </nav>

        <main class="py-6 px-8">
            {% block content %}
            {% endblock %}
        </main>
        <footer class="py-6 px-8 text-center bg-slate-600">
            <p class="text-slate-200">Copyright (c) 2024 - Buy me a noodle</p>
        </footer>
    </body>
</html>

core/templates/core/index.html
{% extends 'core/base.html' %}

{% load static %}

{% block title %}Welcome{% endblock %}

{% block content %}

<div class="py-20 text-center space-y-12">
    <h1 class="text-7xl text-slate-300 font-bold">Get paid for your work!</h1>

    <p class="text-xl text-slate-400">
        This is some random info for content
    </p>

    <a href="{% url 'creator:signup' %}" class="py-8 px-12 inline-block text-xl text-white bg-sky-800 rounded-lg">Create page</a>
</div>

<div class="py-12 bg-slate-800">
    <h2 class="mb-12 text-5xl text-slate-300 text-center font-bold">
        Newest creators
    </h2>

    <div class="px-12 grid grid-cols-4 gap-8">
        {% for creator in creators %}
            <div class="bg-slate-600 rounded-lg">
                <figure>
                    <img src="{{ creator.image.url }}" class="rounded-tr-lg rounded-tl-lg" alt="">
                </figure>

                <div class="py-6 px-8 space-y-6">
                    <h3 class="text-xl text-slate-200 font-bold">{{ creator.title }}</h3>

                    <p class="text-slate-300">{{ creator.description }}</p>

                    <a href="{% url 'creator:creator' creator.pk %}" class="py-4 px-6 inline-block text-xl text-white bg-sky-800 rounded-xl">Read more</a>
                </div>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

creator/templates/creator/creator.html
{% extends 'core/base.html' %}

{% load static %}

{% block title %}{{ creator.title }}{% endblock %}

{% block content %}

<div class="py-20 grid grid-cols-3 items-center">
    <figure class="col-span-1">
        <img src="{{ creator.image.url }}" class="rounded-lg" alt="">
    </figure>

    <div class="col-span-2 space-y-12 text-center">
        <h1 class="text-7xl text-slate-300 font-bold">{{ creator.title }}</h1>

        <p class="text-xl text-slate-400">
            {{ creator.description }}
        </p>
    </div>
</div>

<div class="py-12 bg-slate-800">
    <div class="px-12">
        <h2 class="mb-12 text-5xl text-slate-300 text-center font-bold">Support me!</h2>

        <p class="text-xl text-slate-400 text-center">
            Random info
        </p>

        <div class="mt-12 flex flex-row space-x-4 items-center justify-center">
            <a href="#" class="py-4 px-6 inline-block text-xl text-white bg-sky-800 rounded-lg">
                Buy me "1" noodle $1
            </a>

            <a href="#" class="py-4 px-6 inline-block text-xl text-white bg-sky-800 rounded-lg">
                Buy me "2" noodle $2
            </a>
            
            <a href="#" class="py-4 px-6 inline-block text-xl text-white bg-sky-800 rounded-lg">
                Buy me "5" noodle $5
            </a>
        </div>
    </div>
</div>
{% endblock %}

creator/templates/creator/creators.html
{% extends 'core/base.html' %}

{% load static %}

{% block title %}Creators{% endblock %}

{% block content %}

<div class="py-20 text-center space-y-12">
    <h1 class="text-7xl text-slate-300 font-bold">Creators</h1>
</div>

<div class="py-12 bg-slate-800">
    <div class="px-12 grid grid-cols-4 gap-8">
        {% for creator in creators %}
            <div class="bg-slate-600 rounded-lg">
                <figure>
                    <img src="{{ creator.image.url }}" class="rounded-tr-lg rounded-tl-lg" alt="">
                </figure>

                <div class="py-6 px-8 space-y-6">
                    <h3 class="text-xl text-slate-200 font-bold">{{ creator.title }}</h3>

                    <p class="text-slate-300">{{ creator.description }}</p>

                    <a href="{% url 'creator:creator' creator.pk %}" class="py-4 px-6 inline-block text-xl text-white bg-sky-800 rounded-xl">Read more</a>
                </div>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

creator/templates/creator/edit.html
{% extends 'core/base.html' %}

{% load static %}

{% block title %}Edit{% endblock %}

{% block content %}

<div class="py-20 text-center space-y-12">
    <h1 class="text-7xl text-slate-300 font-bold">Edit</h1>
</div>

<div class="py-12 bg-slate-800 text-blue-500">
    <form method="post" action="." enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="">
            <button class="w-full py-6 px-8 bg-sky-800 text-white font-bold rounded-lg">Submit</button>
        </div>
    </form>
</div>
{% endblock %}

creator/templates/creator/login.html
{% extends 'core/base.html' %}

{% load static %}

{% block title %}Log in{% endblock %}

{% block content %}
<div class="py-20 text-center">
    <h1 class="text-7xl text-slate-300 font-bold">Log in</h1>
</div>

<div class="max-w-lg mx-auto px-8 py-12 bg-slate-800">
    <form method="post" action="." class="space-y-6">
        {% csrf_token %}
        
        <div class="space-y-4">
            <label for="id_username" class="text-white text-lg">Username:</label>

            <input class="w-full py-6 px-8 bg-slate-600 text-white font-bold rounded-lg" type="text" name="username" autofocus="" autocapitalize="none" autocomplete="username" maxlength="150" required="" id="id_username">
        </div>

        <div class="space-y-4">
            <label for="id_password" class="text-white text-lg">Password:</label>
            
            <input class="w-full py-6 px-8 bg-slate-600 text-white font-bold rounded-lg" type="password" name="password" autocomplete="current-password" required="" id="id_password">
        </div>

        {% if form.errors %}
            <div class="py-6 px-8 bg-amber-600 text-white rounded-lg">
                <p>Username or password is not correct</p>
            </div>
        {% endif %}

        <div class="">
            <button class="w-full py-6 px-8 bg-sky-800 text-white font-bold rounded-lg">Submit</button>
        </div>

    </form>
</div>
{% endblock %}

creator/templates/creator/mypage.html
{% extends 'core/base.html' %}

{% load static %}

{% block title %}{{ creator.title }}{% endblock %}

{% block content %}

<div class="py-20 grid grid-cols-3 items-center">
    <figure class="col-span-1">
        <img src="{{ creator.image.url }}" class="rounded-lg" alt="">
    </figure>

    <div class="col-span-2 space-y-12 text-center">
        <h1 class="text-7xl text-slate-300 font-bold">{{ creator.title }}</h1>

        <p class="text-xl text-slate-400">
            {{ creator.description }}
        </p>
    </div>
</div>

<div class="py-12 bg-slate-800">
    <div class="px-12">
        <h2 class="mb-12 text-5xl text-slate-300 text-center font-bold">My supporters</h2>

        <p class="text-xl text-slate-400 text-center">
            Random info
        </p>

        <div class="mt-12 text-center text-white space-y-5">
            <p class="text-xl">john@doe.com - One noodle = $1 {April 12, 2024}</p>

            <hr>

            <p class="text-xl font-bold">Total: $1</p>
            
        </div>
    </div>
</div>
{% endblock %}

creator/templates/creator/signup.html
{% extends 'core/base.html' %}

{% load static %}

{% block title %}Sign in{% endblock %}

{% block content %}
<div class="py-20 text-center">
    <h1 class="text-7xl text-slate-300 font-bold">Sign in</h1>
</div>

<div class="max-w-lg mx-auto px-8 py-12 bg-slate-800">
    <form method="post" action="." class="space-y-6">
        {% csrf_token %}
        
        <div class="space-y-4">
            <label for="id_username" class="text-white text-lg">Username:</label>

            <input class="w-full py-6 px-8 bg-slate-600 text-white font-bold rounded-lg" type="text" name="username" autofocus="" autocapitalize="none" autocomplete="username" maxlength="150" required="" id="id_username">
        </div>

        <div class="space-y-4">
            <label for="id_password1" class="text-white text-lg">Password:</label>
            
            <input class="w-full py-6 px-8 bg-slate-600 text-white font-bold rounded-lg" type="password" name="password1" autocomplete="current-password" required="" id="id_password1">
        </div>

        <div class="space-y-4">
            <label for="id_password2" class="text-white text-lg">Repeat password:</label>
            
            <input class="w-full py-6 px-8 bg-slate-600 text-white font-bold rounded-lg" type="password" name="password2" autocomplete="current-password" required="" id="id_password2">
        </div>

        {% if form.errors %}
            <div class="py-6 px-8 bg-amber-600 text-white rounded-lg">
                <p>Username or password error</p>
            </div>
        {% endif %}

        <div class="">
            <button class="w-full py-6 px-8 bg-sky-800 text-white font-bold rounded-lg">Submit</button>
        </div>

    </form>
</div>
{% endblock %}